/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/macbook.glb -o macbook-temp.js 
Author: M I H (https://sketchfab.com/imamulhasan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-289c013e6c0541f498d4c6b40045db88
Title: MacBook
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/macbook.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.ASSET_MAT_MR} />
        {/* <mesh geometry={nodes.Object_7.geometry} material={materials.ASSET_MAT_MR} /> */}
      </group>
    </group>
  )
}

useGLTF.preload('/macbook.glb')
